### ISSUE TITLE
can I get some  examples about (arrobot_setdigout,arrobot_getdigin, and arrobot_command)

### ISSUE THREAD

**Issue by magedmikhail** [reed-adept/aria-matlab#3]

**Comment by magedmikhail** [comment]
can I get some examples about (arrobot_setdigout,arrobot_getdigin, and arrobot_command)
thank you

**Comment by reed-adept** [comment]
Please see the ARIA C++ API documentation and example programs and robot manual (ArRobot::getDigIn(), DIGOUT command, ArRobot::com(), ArRobot::comInt(), ArRobot::com2Bytes()).  

If you have a specific bug or problem using these in matlab, you can reopen this issue or discuss on the aria-users mailing list http://robots.mobilerobots.com/wiki/aria-users

**Comment by magedmikhail** [comment]
Hello, Reed
thanks so much for quick response, actually I am struggling with
arrobot_setdigout and arrobot_command commands
I tried arrobot_command('MOVE',300) and many so many it did not work. just
I need from you one example only and I will figure it out by my self
thanks again,
maged

On Mon, Nov 4, 2013 at 3:18 PM, Reed Hedges notifications@github.comwrote:

> Please see the ARIA C++ API documentation and example programs and robot
> manual (ArRobot::getDigIn(), DIGOUT command, ArRobot::com(),
> ArRobot::comInt(), ArRobot::com2Bytes()).
> 
> If you have a specific bug or problem using these in matlab, you can
> reopen this issue or discuss on the aria-users mailing list
> http://robots.mobilerobots.com/wiki/aria-users
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/reed-adept/aria-matlab/issues/3#issuecomment-27723431
> .

## 

Thanks,
Dr. Maged mikhail
Maged B. Mikhail  Ph.D.
Tennessee State University
Dept. of Electrical and Computer Engr.
Intelligent Control Systems Lab Rm. 201
Work: (615) 963-5328
Cell: (615) 710-6745
E_mail: mmikhail@my.tnstate.edu mmikhail@mytsu.tnstate.edu

**Comment by reed-adept** [comment]
The first argument to arrobot_command is the command number (integer), not a string.  You can find the commands listed in the robot manual.

There is an arrobot_move function however, which sends the MOVE command via ARIA.

Reed

**Comment by magedmikhail** [comment]
thanks again Mr.Reed
I did like what mentioned but still the problem.
 For example when I execute arrobot_move(200), it worked fine, but
arrobot_command(8,200) didn't work.
also, how can I open-close-the gripper using arrobot_command, I did
arrobot_command(33,1) but it did not work.
thanks again for your help
maged

On Tue, Nov 5, 2013 at 1:49 PM, Reed Hedges notifications@github.comwrote:

> The first argument to arrobot_command is the command number (integer), not
> a string. You can find the commands listed in the robot manual.
> 
> There is an arrobot_move function however, which sends the MOVE command
> via ARIA.
> 
> Reed
> 
> From: magedmikhail [mailto:notifications@github.com]
> Sent: Tuesday, November 05, 2013 1:47 PM
> To: reed-adept/aria-matlab
> Cc: Reed Hedges
> Subject: Re: [aria-matlab] can I get some examples about
> (arrobot_setdigout,arrobot_getdigin, and arrobot_command) (#3)
> 
> Hello, Reed
> thanks so much for quick response, actually I am struggling with
> arrobot_setdigout and arrobot_command commands
> I tried arrobot_command('MOVE',300) and many so many it did not work. just
> I need from you one example only and I will figure it out by my self
> thanks again,
> maged
> 
> On Mon, Nov 4, 2013 at 3:18 PM, Reed Hedges notifications@github.comwrote:
> 
> > Please see the ARIA C++ API documentation and example programs and robot
> > manual (ArRobot::getDigIn(), DIGOUT command, ArRobot::com(),
> > ArRobot::comInt(), ArRobot::com2Bytes()).
> > 
> > If you have a specific bug or problem using these in matlab, you can
> > reopen this issue or discuss on the aria-users mailing list
> > http://robots.mobilerobots.com/wiki/aria-users
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/reed-adept/aria-matlab/issues/3#issuecomment-27723431>
> > .
> 
> ## 
> 
> Thanks,
> Dr. Maged mikhail
> Maged B. Mikhail Ph.D.
> Tennessee State University
> Dept. of Electrical and Computer Engr.
> Intelligent Control Systems Lab Rm. 201
> Work: (615) 963-5328
> Cell: (615) 710-6745
> E_mail: mmikhail@my.tnstate.edu mmikhail@mytsu.tnstate.edu
> 
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/reed-adept/aria-matlab/issues/3#issuecomment-27800464>.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/reed-adept/aria-matlab/issues/3#issuecomment-27806019
> .

## 

Thanks,
Dr. Maged mikhail
Maged B. Mikhail  Ph.D.
Tennessee State University
Dept. of Electrical and Computer Engr.
Intelligent Control Systems Lab Rm. 201
Work: (615) 963-5328
Cell: (615) 710-6745
E_mail: mmikhail@my.tnstate.edu mmikhail@mytsu.tnstate.edu
